### ISSUE TITLE
[Feature Request] Setting for customizing API host to be available to more areas. 

### ISSUE THREAD

**Issue by LionChenA** [piazzatron/anki-smart-notes#14]
1. This change would greatly increase the plugin's usability, especially for users in China. Allowing customization of the API host ensures accessibility in regions with restricted internet access. 
2. Additionally, this modification is relatively simple compared to other complex features, involving just a configuration option in the settings.

**Comment by LionChenA** [comment]
It's a screenshot of settings of [chatbox](https://github.com/Bin-Huang/chatbox).
![CleanShot 2024-07-05 at 01 36 31@2x](https://github.com/piazzatron/anki-smart-notes/assets/66246210/0fff1daf-c377-4e02-b545-bd7e180e2764)

**Comment by piazzatron** [comment]
Good idea. Will implement this in the next version 👍

**Comment by piazzatron** [comment]
Implemented in v1.4.0! Let me know if this did the trick @LionChenA
