### ISSUE TITLE
request for azure openAPI

### ISSUE THREAD

**Issue by xinwangseu** [piazzatron/anki-smart-notes#15]
I would greatly appreciate it if you could add support for the Azure OpenAI API. Thank you!

**Comment by piazzatron** [comment]
Hey @xinwangseu, I can add this. Can you help me understand the use case a bit? Is it that you already have an API key for Azure and don't want to purchase another for OpenAI (valid), or something else?

**Comment by xinwangseu** [comment]
In China, I am unable to pay for the OpenAI API as it shows my credit card is declined. However, payment for the Azure OpenAI API works without any problems.

**Comment by piazzatron** [comment]
That makes sense. In the short term I will implement the feature request from [here](https://github.com/piazzatron/anki-smart-notes/issues/14) to support other URLs for the OpenAI API, which should unblock China users. Mid term I will implement support for other models including the Azure OpenAI API, which has some slight differences from the official OpenAI API.

**Comment by piazzatron** [comment]
@xinwangseu I've implemented API override described here: https://github.com/piazzatron/anki-smart-notes/issues/14

**Comment by xinwangseu** [comment]
look for your help，I have filled in the endpoint URL for Azure OpenAI and entered the API key, but I encountered the above error during testing
<img width="280" alt="未命名图片" src="https://github.com/user-attachments/assets/2d02f1e8-bd54-4211-ad89-be3ee8a85258">

**Comment by piazzatron** [comment]
Hi @xinwangseu, sorry for confusion - Azure has a different API structure than the original OpenAI API, so it won't work as an override URL. You'll need to find a provider that matches the OpenAI API exactly.

If you can hold out a week or two though, I have a fix coming that will support users who can't access OpenAI in their countries without the need for this override URL.

**Comment by xinwangseu** [comment]
appreciate it

**Comment by xinwangseu** [comment]
Hi @piazzatron ，looking forward to that new feature update

**Comment by piazzatron** [comment]
Hey @xinwangseu - will be out in the next few days :) Ended up being a much bigger lift than I expected!

**Comment by piazzatron** [comment]
@xinwangseu, new version is out now (might take Anki 24hr to update, or you can tell it to update all add-ons).

New version is subscription based & requests to OpenAI & Anthropic go through me, so no more geo restriction 🤙
