### ISSUE TITLE
[Bug Report] Cannot set api key

### ISSUE THREAD

**Issue by LionChenA** [piazzatron/anki-smart-notes#16]
I have found some bugs while testing the new feature. The custom API key isn't being saved properly. Same issue found on both win and mac.

When making other changes to the configuration, the API key returns to blank. It seems that the default settings cannot be replaced correctly. There was an instance where restoring defaults was not functioning properly, and the custom API key was replaced with a made-up key (no recording and no repetition).

https://github.com/piazzatron/anki-smart-notes/assets/66246210/3fb991d5-7d3a-4275-9dea-8eab46cc3ec6

https://github.com/piazzatron/anki-smart-notes/assets/66246210/b6ebd7cd-9183-4efe-bcdd-0ade32753e55

**Comment by piazzatron** [comment]
Oops - thanks for flagging + including videos, will get this fixed tmrw.

**Comment by piazzatron** [comment]
Resolved in v.1.4.1
