### ISSUE TITLE
[Feature Request] Claude / Anthropic API Support

### ISSUE THREAD

**Issue by kacperpaluch** [piazzatron/anki-smart-notes#18]
Do you have any plans to add support for Claude / Anthropic API?

**Comment by piazzatron** [comment]
Definitely. Plan to add Claude/Gemini in the future

**Comment by wadid** [comment]
Very interesting are also the versions of Openrouter which are called "moderated". these are very easy to jailbreak.

[[anthropic/claude-3-sonnet:beta](https://openrouter.ai/models/anthropic/claude-3-haiku)](https://openrouter.ai/models/anthropic/claude-3-haiku)

just add a prefill assistant message to them:
https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/prefill-claudes-response

**Comment by piazzatron** [comment]
Claude coming in the next version in a couple weeks!

**Comment by piazzatron** [comment]
Hey @kacperpaluch, just released version 2.0 (if you refresh your addons in Anki), which supports Claude Sonnet 3.5 and Haiki 3.0.

**Comment by wadid** [comment]
Great!!!! :) Regarding the prefilling... something like the following is not possible I guess? https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/prefill-claudes-response

**Comment by piazzatron** [comment]
It would be possible (as well as inputting system messages to influence general behavior) - can you give me an example of what you're trying to accomplish with this?

**Comment by wadid** [comment]
haha... just if you want to include banned stuff in your cards :D
