### ISSUE TITLE
Keep getting the "cant reference other smart fields" error when trying to map notes

### ISSUE THREAD

**Issue by gianni1969420** [piazzatron/anki-smart-notes#2]
Hello, Every time I attempt to map new note fields i get the above issue. How could I solve it? Thank!

**Comment by piazzatron** [comment]
Hi - sorry you're experiencing this. I'm not sure if it's a bug or just unclear documentation on my part; you can't reference another AI generated field in a prompt. 

Do you mind sending me a screenshot of the prompt you're trying to use, the card's fields, and any existing prompts you have? I'll investigate.

**Comment by piazzatron** [comment]
Hi Jonathan – I can't see the screenshot, I think you have to post it directly on Github here versus replying via email!

**Comment by gianni1969420** [comment]
Hi Mike,The error message is as follows: “ Error: 404, message='Not Found', url=URL('https://api.openai.com/v1/chat/ completions)” I can still post a screenshot if need be in the morning. Thanks! El jun 13, 2024, a la(s) 10:42 p.m., Michael Piazza ***@***.***> escribió:﻿
Hi Jonathan – I can't see the screenshot, I think you have to post it directly on Github here versus replying via email!

**Comment by piazzatron** [comment]
Wow, you're getting a 404 trying to hit OpenAI 👀. 

Is this a different error than the original error about setting a smart field as a target? Screenshots would def help, thx. You were able to get set up properly with an API key?

**Comment by gianni1969420** [comment]
![Screenshot 2024-06-14 084108](https://github.com/piazzatron/anki-smart-notes/assets/108819334/b46a928f-f885-4747-a860-182fb42832ed)
 Hello, yes, this is different. I have tried with several API keys that I have generated and am not running a VPN.

**Comment by piazzatron** [comment]
Got it, thanks for the screenshot. Investigating today. What region are you in? Want to ensure OpenAI is enabled for you.

**Comment by gianni1969420** [comment]
I am located in the US

Στις Παρ 14 Ιουν 2024 στις 1:32 μ.μ., ο/η Michael Piazza <
***@***.***> έγραψε:

**Comment by gianni1969420** [comment]
But when I switch to GPT3.5 i get this "

Smart Notes error: OpenAI rate limit exceeded. Wait a few minutes and try
again".

Chat GPT works fine for me normally.

Στις Παρ 14 Ιουν 2024 στις 4:11 μ.μ., ο/η Ioannis Mixelvis <
***@***.***> έγραψε:

**Comment by piazzatron** [comment]
Oh, interesting. If you wait a few minutes with GPT-3.5, does it eventually work?

Have you paid for your open AI key? Only paid accounts can use GPT4 and the like.

**Comment by gianni1969420** [comment]
I have ChatGPT premium. Would I need to pay separately for the keys? None of the models work, even 3.5. I tried a clean install of Anki. El jun 15, 2024, a la(s) 1:50 a.m., Michael Piazza ***@***.***> escribió:﻿
Oh, interesting. If you wait a few minutes with GPT-3.5, does it eventually work?
Have you paid for your open AI key? Only paid accounts can use GPT4 and the like.

**Comment by piazzatron** [comment]
Investigated this a bit more – you'll need to pay for an API key, apparently there's no OpenAI free tier, despite their docs suggesting otherwise. It's different than paying for ChatGPT premium, unfortunately. Will update the docs for the addon to reflect this.

Going to close this one out, feel free to reopen if you're still running into issues.
