### ISSUE TITLE
Batch processing around 200 cards with 2k to 4k tokens for each card hits rate limits a lot

### ISSUE THREAD

**Issue by wadid** [piazzatron/anki-smart-notes#21]
I just tried to batch process a deck with around 200 cards. The generated content is around 2k to 4k tokens per card. Unfortunately I had to restart the batch process I guess 10 times  until it was done as it seems it hit rate limits.

Is there a possibility to add an option that it will just redo the request until its done or resend the request automatically? Even if that would mean idle and wait times (because of rate limit), it would still be better than needing to manually restart the process. Because if it cancels 10 times it means you need to sit 20 minutes at the computer to restart the process instead of just having the processing run by itself.

I guess resend the request and not overwrite the already generated fields might do it?

**Comment by piazzatron** [comment]
Wow, 2k-4k tokens per card! I'd be interested to learn more about your usecase, sounds interesting.

Can you confirm which version of the plugin you're on? It should say in settings, towards the bottom. I know users have batch processed 10k card decks w/o issue, but your large token sizes are probably exercising the batching system in new ways. It already has retries with backoff, so probably just need to increase the retry count.

**Comment by wadid** [comment]
thx! ahhh just realized how expensive that is. before I used for api stuff claude haiku which costs $0.25 | $1.25.
chatgpt 4o costs $5 | $15.  which would mean 200 cards might cost me 15 $. A bit expensive :-D

Basically I like to add to language cards for example context when to use a sentence... then declination table for the verbs. grammar explanations. Also I learn mostly whole sentences which means there is a lot to explain. So input and output is quite long.

Or for example geography cards, you can add a lot of interesting information. culuter, economy, interesting facts...

For IT concepts you can add scenarios or best practices. code explanations. and so on....

but a bit expensive with 4o as I just realized :D

**Comment by wadid** [comment]
btw its the newest version. The one that just got released and works with
empty fields. Otherwise the deck wouldnt have processed.

**Comment by piazzatron** [comment]
Thanks for explaining, really cool to see this used on some non-language-learning use cases.

I'm working on Claude integration but for now, try running it with GPT 3.5 (advanced settings). About 10x cheaper than 4o :)

**Comment by wadid** [comment]
I noted that its quite difficult for me to get very good results with long and complicated prompts. The results I get from the openAI API are less complex and detailed compared to when I would run the prompt in the browserinterface.

Not sure if I need to tweak my prompt more or what to do....

The result that I get from OpenAPI is in some cases not sufficient for some of the stuff that I do.

For example when it should explain some code I want that it introduces some general explanations or theoretical background information to understand some of the concepts of the code better.

With OpenAI API the background information is then too generic. While with ChatGPT the result is often more detailed and more specific and really gets the missing things that you need to know....

Do you know more about it?

**Comment by piazzatron** [comment]
A few different things could be responsible: 

Model: ChatGPT uses the GPT-4o model under the hood, so if you select GPT-4o in settings, that should be the same. 

Temperature: controls how 'random' the responses are. SmartNotes uses default temperature of 0 (low randomness). Try playing around with this in the OpenAI API; future versions of Smart Notes will support changing temperature. ChatGPT may use a higher default temperature (0.7?), I'm seeing conflicting info here.

Prompt: ChatGPT probably prefixes your prompt with some additional info. Eventually I'll have this feature in SmartNotes too. For now, try adding something like they do here: https://community.openai.com/t/differences-in-api-response-and-web-response/298828/10
