### ISSUE TITLE
Button "Generate smart field" doesn't work

### ISSUE THREAD

**Issue by kacperpaluch** [piazzatron/anki-smart-notes#22]
It's me again with another problem :)

I have 1 huge template.

In Anki Smart Notes I have it set up to generate 'def1', 'p1' and 'kol1' on the basis of 'ang' and 'pol1'.
On the basis of "ang" and "pol2" the fields "pol2", "def2" and "kol2" etc. should be generated until we reach "pol3" and "pol4".

As you can see from my screenshot the field "ang" = "walfare bill" has only one meaning in Polish so "pol1" = "ustawa o opiece społecznej" and "pol2", pol3", "pol4" are empty.

If I click the "Generate Smart Field" icon (marked as 1 in the screenshot) nothing happens. If I right-click on each field - "def1", "p1", "kol1" and select "Generate Smart Fields" (marked as 2 in the screenshot) from the context menu then everything works OK.

Anki Smart Notes v 1.5

<img width="992" alt="Zrzut ekranu 2024-07-16 o 15 05 49" src="https://github.com/user-attachments/assets/016317b9-3121-4143-b0b3-b365cca8b7a4">

**Comment by piazzatron** [comment]
Fun! Can you post screenshots of your prompts as well so I can try to repro on my end? 

(I assume you've marked the smart fields you want to generate as allowing empty fields in settings)

**Comment by kacperpaluch** [comment]
For target field p1:
```
Uczę się języka angielskiego i jestem na poziomie B1 / B2. Podam ci słówko angielskie oraz jego tłumaczenie.
Podaj mi 3 przykłady użycia tego słowa. Do każdego przykładu powinieneś napisać też tłumaczenie - najpierw napisz przykładowe zdanie po angielsku a następnie od razu po tym napisz jego tłumaczenie na język polski. Pamiętaj aby tłumaczenia przykładów umieścić w nawiasach.

Pamiętaj żeby każdy przykład napisać w nowej linii - wstaw pomiędzy przykłady znacznik <br>, ale pamiętaj żeby po ostatnim przykładzie nie wstawiać <br>.
Słówko po angielsku: {{ang}}
Tłumaczenie na język polski: {{pol1}}
```
for target field p2 replace {{pol1}} to {{pol2}} etc

For target field def1
```
Wyobraź sobie, że jesteś nauczycielem języka angielskiego a ja twoim uczniem. Jestem teraz na poziomie B2 (średniozaawansowany).
Podam ci słówko angielskie oraz jego polskie znaczenie. Twoim zdaniem jest napisać definicję tego słówka taką jaką mogę znaleźć w słowniku dla osób, które uczą się angielskiego. Pamiętaj, że pisząc definicję nie powinieneś w niej użyć tego słowa o które cie proszę! W odpowiedzi podaj mi samą definicję i nie pisz nic więcej.
Słówko po angielsku: {{ang}}
Tłumaczenie na język polski: {{pol1}}
Pamiętaj, że definicja którą mi napiszesz powinna być ściśle powiązana z polskim tłumaczeniem {{pol1}}
```
for target field def2 replace {{pol1}} to {{pol2}} etc

For target field kol1
```
Wyobraź sobie, że jesteś nauczycielem języka angielskiego a ja twoim uczniem. Nauczyłem sie nowego słówka, podam ci słówko po angielsku oraz jego znaczenie. Twoim zdaniem jest podanie mi najważniejszych kolokacji oraz ich tłumaczenia na język polski z tym słowem.
Jako odpowiedź napisz mi kolokacje z tłumaczeniami bez dodatkowych komentarzy.
Pamiętaj żeby każdą kolokacje napisać w nowej linii - wstaw pomiędzy kolokacje znacznik <br>, ale pamiętaj żeby po ostatniej kolokacji nie wstawiać <br>.
Słowo po angielsku: {{ang}}
Tłumaczenie na język polski: {{pol1}}
```
for target field kol2 replace {{pol1}} to {{pol2}} etc

<img width="672" alt="Zrzut ekranu 2024-07-17 o 06 55 48" src="https://github.com/user-attachments/assets/44780a68-dbdc-4d09-9984-e7c431d8667d">
<img width="839" alt="Zrzut ekranu 2024-07-17 o 06 58 35" src="https://github.com/user-attachments/assets/8f82eb54-6dde-4b8c-af3b-b7baf05d0f8a">
<img width="750" alt="Zrzut ekranu 2024-07-17 o 06 58 42" src="https://github.com/user-attachments/assets/a6969dd8-173a-4662-b58c-8ed6cdb0cfb2">

**Comment by kacperpaluch** [comment]
@piazzatron here is my deck and settings file from Anki Smart Notes
[deck.zip](https://github.com/user-attachments/files/16311644/deck.zip)
[meta.json](https://github.com/user-attachments/files/16311646/meta.json)

**Comment by piazzatron** [comment]
Thanks for sending, will look today and get back to you

**Comment by piazzatron** [comment]
OK, I think this is a confusing named UI element causing the issue here. You have 'Always Generate Smart Field' turned off, which means that the field will *only* be generated by a manual right click. I see why this was confusing 🫤

If I negate it, calling it "Require right click manual generation" and have it default off, would that be clearer?

**Comment by kacperpaluch** [comment]
> OK, I think this is a confusing named UI element causing the issue here. You have 'Always Generate Smart Field' turned off, which means that the field will _only_ be generated by a manual right click. I see why this was confusing 🫤
> 
> If I negate it, calling it "Require right click manual generation" and have it default off, would that be clearer?

Oh, so I've just misunderstood settings :) Thanks for your help!

**Comment by piazzatron** [comment]
Np! Confusing name. I'm clarifying it in 1.6.0
