### ISSUE TITLE
API KEY doesn't work

### ISSUE THREAD

**Issue by kdjcjedcksdnc** [piazzatron/anki-smart-notes#23]
Hello,

I am unfamiliar with programming and therefore don't know if this is a problem with an obvious fix.

My problem is: There happens nothing at all. The Add on simply produces no content.

- I added my credit card to my OPENAI Account
- I created multiple API KEYS (none of them worked)
- I restarted ANKI multiple times
- I added 10$ to my account

Still nothing happened...

It seems to me that the problem has to do with the fact that my account is in the free tier category.

I don't know what that means and why there are such categories.

Apparently you will migrate into a new category after you have spent 5$ with the API. But how am I supposed to do that when the API doesn't work? It's all mysterious to me.

If someone else encountered this same problem and there is an easy fix I would highly appreciate if you could write a quick response how this can be fixed.

Thanks !

**Comment by piazzatron** [comment]
Hi @kdjcjedcksdnc, sorry you're running into trouble. When you say nothing happened, what exactly do you mean? If you try to create a prompt and then run 'Test Prompt', what do you see? Can you give me an example of the prompt you're trying?

Adding $10 to OpenAI should be fine.

**Comment by kdjcjedcksdnc** [comment]
Hey,

first of alle thank you so much for your support and great project in the first place:

Here is some further information

- I am on Mac with a M1 Chip
- Sonoma 14.4.1

Anki:
- Version ⁨23.12.1 (1a1d4d54)⁩
- Python 3.9.15 Qt 6.5.3 PyQt 6.5.3

And I've added more than 20$ to my OPEN AI Account and already used something for TTS.

And oddly this API action worked from my machine not merely through the API Playground on the website. So the API seems to be working.

Also because I used the API for TTS and thus spent some money I upgraded into 'Tier 1'.

Now in Anki the 'Test Prompt' works but it still doesn't work when adding a card or in the library.

**Comment by piazzatron** [comment]
Hey @kdjcjedcksdnc for some reason I got a reply from you via Github email, that isn't appearing here... strange. Anyways:

If you try right clicking the field you want generated in the Anki editor and then generating it there, does it work? I wonder if you had 'Always Generate' turned off on the prompt - this was some confusingly named UI on my part, clarified in version 1.6.2.

If that's not it, if you could upload a video of the prompt + an example card that doesn't generate, I can help debug further

**Comment by kdjcjedcksdnc** [comment]
Hey, thank you very much for your effort.

Actually it worked even before you updated the add on. So I think it had to do with my API. Also I had not checked the box (in the old add on) so that also might have been the problem. And yes you are right it was kind of unclear. Now it es very clear. Thank You again! The Add on is very helpful.

**Comment by piazzatron** [comment]
Great! Glad to hear it's working and useful :)
