### ISSUE TITLE
[Feature Request] Different Smartnotes for decks that have same notetype

### ISSUE THREAD

**Issue by wadid** [piazzatron/anki-smart-notes#24]
I use a generic Note type for different content types in my Anki decks, such as AWS Questions and Java Questions. Both decks use the same card type but need different prompts.

**Here’s my proposed solution:**

- Default State: By default, a deck is deactivated for card generation.
- Activation Button: Include a button to activate a deck for smart note generation.
- Individual Prompts: Allow the possibility to set an individual prompt for each deck that can override the global prompt for the Note type.
- Global Prompt: A general prompt used for card generation if no individual prompt is set for a deck.

**Process:**

When generating cards, first check if the deck is activated.

- If the deck is deactivated, do nothing.
- If the deck is activated, check for an individual prompt.
- If an individual prompt is present, use it.
- If no individual prompt is present, use the global prompt.

**Comment by piazzatron** [comment]
@wadid this is a good callout, thanks for describing a potential solution. Definitely need some functionality to better support reusing card types between decks, this is on my radar and will be included in a future version.

**Comment by piazzatron** [comment]
Hey @wadid, this is out today in v2.2.1 for subscribers/users on free trial. Going to close this one out
