### ISSUE TITLE
[Feature Request] support for GPT-4o mini

### ISSUE THREAD

**Issue by kacperpaluch** [piazzatron/anki-smart-notes#25]
Another feature request. This time probably the easiest one to add.

OpenAI annouced GPT-4o mini model, are you going to add it to Anki Smart Notes?

I have edited 2 files: 
- config.py (line: OpenAIModels =)
- addon_options_dialog.py (line: openai_models: List[OpenAIModels] =)

and I have just added "gpt-4o-mini" and it is working fine (probably) :)

**Comment by piazzatron** [comment]
You're fast!! Yes, will have mini 4o in the next version. Probably will just replace 3.5 with it

**Comment by piazzatron** [comment]
Out in 1.6.2! @kacperpaluch make sure you have 1.6.2 and not 1.6.0 / 1.6.1, I introduced some new logging in 1.6.0 that had some issues (fixed now)
