### ISSUE TITLE
Got a problem when clicking the "New Text Field" button

### ISSUE THREAD

**Issue by samon127** [piazzatron/anki-smart-notes#29]
Here is the Debug Info:

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.6.1-arm64-arm-64bit

Traceback (most recent call last):
  File "/Users/builder/Library/Application Support/Anki2/addons21/1531888719/src/ui/addon_options_dialog.py", line 124, in <lambda>
    add_button.clicked.connect(lambda _: self.on_add(False))
  File "/Users/builder/Library/Application Support/Anki2/addons21/1531888719/src/ui/addon_options_dialog.py", line 487, in on_add
    config.openai_api_key = self.api_key_edit.text()
AttributeError: 'AddonOptionsDialog' object has no attribute 'api_key_edit'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Anki Quick AI ['547821970', 2024-07-11T15:06, 'None', '']
AnkiBrain AnkiChatGPT - GPT-4 GPT 35 with auto-cards and document analysis ['1915225457', 2024-09-06T08:58, 'None', '']
HyperTTS - Add speech to your flashcards ['111623432', 2024-08-12T15:48, 'None', mod]
JapaneseFurigana ['678316993', 2024-08-06T00:46, 'None', '']
Smart Notes - AI Notes  TTS with with ChatGPT-4o Claude ElevenLabs etc ['1531888719', 2024-09-07T08:51, 'None', mod]

===IDs of active AnkiWeb add-ons===
111623432 1531888719 1915225457 547821970 678316993

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Fast Word Query Multi-threaded queries for words from local or web dictionaries ['1807206748', 2019-06-23T12:10, 'None', '']

**Comment by piazzatron** [comment]
Taking a look, thanks for sending lots

**Comment by piazzatron** [comment]
Oof, bad one. New version is out. Extended free trials for everybody. Thanks again for flagging.

**Comment by samon127** [comment]
Thank you, problem solved~
