### ISSUE TITLE
TTS support

### ISSUE THREAD

**Issue by cantalupo555** [piazzatron/anki-smart-notes#3]
Would it be possible to add TTS support?
https://platform.openai.com/docs/guides/text-to-speech

Thanks for the add-on.

**Comment by piazzatron** [comment]
I was thinking of supporting this in the future. I'll add it in a future version :)

In the mean time, I've been using the system TTS. It's not great but you can define it in your cards editor like so:
`{{tts ja_JP:ExampleTTS}}`. More info here: https://docs.ankimobile.net/tts.html

**Comment by piazzatron** [comment]
Hey @cantalupo555, as I'm thinking about implementation I'd love to know a little bit more about how you're imagining using this one. Were you imagining something like a smart field with an audio type instead of a text type (the rest of the prompt behavior staying the same), or more akin to an option to read out any existing field using TTS?

**Comment by cantalupo555** [comment]
I'm using [Language Tools](https://ankiweb.net/shared/info/771677663).
It automates the creation of my language deck. Just like the translation... and TTS.

https://youtu.be/OrQTHFxSS0Q&t=78

![image](https://github.com/piazzatron/anki-smart-notes/assets/12485871/e2d78f1c-063b-4e4d-811f-39cd36a769a8)

![image](https://github.com/piazzatron/anki-smart-notes/assets/12485871/cbf945e8-67ff-4519-85ab-1836788b98f6)

**Comment by piazzatron** [comment]
Interesting – could definitely add something like this.

As it stands, does this add-on play well with Language Tools?

**Comment by werererer** [comment]
I am using it in a similar fashion actually.

1. Fill out one field with relevant information
2. Let all the other fields Autogenerate.

And I am doing this like very quickly.

Currently using chinese support plugin for the aufio thought. Having a single plugin would ofc streamline everything.

https://ankiweb.net/shared/info/1752008591

**Comment by hienstorfer** [comment]
Text do speech is already there: hypertts. It really works well with Azure, ElevenLabs et al.
https://ankiweb.net/shared/info/111623432

**Comment by piazzatron** [comment]
Re the above, I agree it would be compelling to have TTS + Language tools functionality in a single add-on, thought it would expand the scope of this project significantly. I'll probably do it anyways.

**Comment by piazzatron** [comment]
Update on TTS - I'm working on this for the next major release (v2), targeting a couple weeks from today. If there are any specific TTS features from AwesomeTTS/HyperTTS/Language Tools that you'd like to see included in Smart Notes, let me know.

**Comment by piazzatron** [comment]
V2 is out today with TTS from Google, ElevenLabs, and OpenAI (more providers to come in the future).

@cantalupo555 and @werererer - I'd love to know if this plugin could replace your Language Tools subscription, and if not, what features we'd need to close the gap. Cheers, thanks in advance for the feedback 🥂
