### ISSUE TITLE
A bug on Test Voice

### ISSUE THREAD

**Issue by samon127** [piazzatron/anki-smart-notes#33]
I was testing on the reading of spelling, I found the Test Voice got a bug like this

![image](https://github.com/user-attachments/assets/38c4d2f9-b1d5-4d36-950b-c126e4c4e3d3)

The Openai model is functional, but they can't read these formats correctly:

A A B B C
A-A-B-B-C
A;A;B;B;C

**Comment by piazzatron** [comment]
Hey Marvin,

Thanks for flagging. Will take a look soon and get back to ya.

**Comment by samon127** [comment]
Excellent~ Both problem solved~
