### ISSUE TITLE
Remove HTML tags during TTS

### ISSUE THREAD

**Issue by libukai** [piazzatron/anki-smart-notes#34]
Many automatically generated cards via plugins will have HTML tags appended.
It is recommended to remove all tags when performing TTS speech synthesis to ensure the generated speech meets expectations.

**Comment by piazzatron** [comment]
Good callout, will add this in the near future.

For now, as a workaround you can create a field on your card with a prompt to remove all HTML in the field you want to speak (doesn't have to be a visible field), use a fast/cheap model like 4o-mini, and then wire *that* field up to the TTS field.

**Comment by libukai** [comment]
Yes, I'm currently using this workflow, and I hope the new features will be launched soon

**Comment by libukai** [comment]
When will this feature be added, like HyperTTS?

![CleanShot 2024-10-12 at 11 12 45@2x](https://github.com/user-attachments/assets/43ec940e-3f59-4423-9968-d4f39deaad4d)

**Comment by piazzatron** [comment]
Should be this coming week :)

**Comment by piazzatron** [comment]
This is out in 2.3.0+! Take it for a spin and let me know how it works for you.
