### ISSUE TITLE
The title of “Card Type” in the new field form should be "Note Type"

### ISSUE THREAD

**Issue by libukai** [piazzatron/anki-smart-notes#35]
![CleanShot 2024-09-27 at 15 29 10@2x](https://github.com/user-attachments/assets/a5ca78be-a8a9-4533-b4de-d525ec7a4d12)

**Comment by piazzatron** [comment]
Good eye! Fixed in the next version

**Comment by libukai** [comment]
And what's the `👏 per-deck 👏 Smart Fields`?

**Comment by piazzatron** [comment]
Those are Smart Fields that are tied to a particular deck, allowing you to reuse note types for different decks. Just went out today 🤙
