### ISSUE TITLE
TTS Model options cannot be saved

### ISSUE THREAD

**Issue by libukai** [piazzatron/anki-smart-notes#36]
![CleanShot 2024-09-29 at 13 22 49@2x](https://github.com/user-attachments/assets/1332302b-1b9c-4c1b-9bec-10336fb75686)

Cannot save Voices options in either the Default or Note interface

**Comment by piazzatron** [comment]
Taking a look 👍

**Comment by piazzatron** [comment]
Fixed in 2.2.2 - I think this one had been around for a while (under the hood it was actually set, but the UI wouldn't update here). Thanks for finding this one! Please re-open if you're still facing issues.
