### ISSUE TITLE
A cache problem

### ISSUE THREAD

**Issue by samon127** [piazzatron/anki-smart-notes#37]
This is the task:
![image](https://github.com/user-attachments/assets/70e1b69b-81b8-448b-8b4d-551605576fab)

The first run was successful, and the result was not good enough, so I 1) Notes -> Find and Replace the "Example Sentence" field with .* -> empty, and 2) modified the prompt, after that, I rerun the task, then I got this immediately:
![image](https://github.com/user-attachments/assets/ca4a44f4-560e-420d-9459-74742e9118fe)

But actually it didn't rerun the 100 words for me, so I guess there is a cache problem maybe~

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.6.1-arm64-arm-64bit

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Anki Remote - Customize ['693153301', 2024-08-03T08:25, 'None', mod]
Contanki - Controller Support for Anki beta ['1898790263', 2024-03-01T10:22, 'v1.0.2', '']
HyperTTS - Add speech to your flashcards ['111623432', 2024-09-30T14:32, 'None', mod]
JapaneseFurigana ['678316993', 2024-08-06T00:46, 'None', mod]
Smart Notes - AI Notes  TTS with with ChatGPT-4o Claude ElevenLabs etc ['1531888719', 2024-09-30T14:15, 'None', mod]

===IDs of active AnkiWeb add-ons===
111623432 1531888719 1898790263 678316993 693153301

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Fast Word Query Multi-threaded queries for words from local or web dictionaries ['1807206748', 2019-06-23T12:10, 'None', '']

**Comment by piazzatron** [comment]
Hey @samon127, I suspect what's going on is that the Example Sentence field isn't empty. When it runs in batch mode it will only fill empty fields to avoid overwriting existing fields. You can also go to `Advanced -> Regenerate all smart fields when batch processing` and that will overwrite any fields, even if they are filled.

Let me know if this fixes it! This behavior should be more discoverable to users.

**Comment by samon127** [comment]
It works after I select "Advanced -> Regenerate all smart fields when batch processing"

Thank you so much :~

**Comment by piazzatron** [comment]
Glad to hear 🍻
