### ISSUE TITLE
Unable to locate the notes, but I do have notes.

### ISSUE THREAD

**Issue by RichardMadden** [piazzatron/anki-smart-notes#38]
![WX20241003-174041@2x](https://github.com/user-attachments/assets/f249babe-b585-4225-b686-ec573508a61b)
![WX20241003-174009@2x](https://github.com/user-attachments/assets/83d07dbe-a030-4d86-ae05-309649964cbb)

**Comment by piazzatron** [comment]
Will take a look, thanks for reporting

**Comment by piazzatron** [comment]
Closed this one out in email thread. Would have affected any users testing notes in custom decks that were at the top of the deck tree.
