### ISSUE TITLE
If there are too many fields in the note template, the Prompt input box will be obscured

### ISSUE THREAD

**Issue by libukai** [piazzatron/anki-smart-notes#39]
![CleanShot 2024-10-10 at 16 48 15@2x](https://github.com/user-attachments/assets/2ea416f6-2b93-479e-9e93-0234dc5f980d)

**Comment by piazzatron** [comment]
Wow, that's a lot of fields 🤯

Will fix

**Comment by jhhr** [comment]
How about making the note fields accessible from a right click menu in the QTextEdit? That is, you place the cursor where you want to add a note field reference, then right click and select the field to paste in the cursor position. That way, even dozens of fields will be easily accessible and they take no space in the editor view.

I made a custom QTextEdit component that works like that in my personal addon:
https://github.com/jhhr/custom-fetch-template-field/blob/main/ui/pasteable_text_edit.py

**Comment by piazzatron** [comment]
@jhhr fantastic idea. Will definitely add this 👍

**Comment by piazzatron** [comment]
@libukai fixed this in 2.4.0 just now. Going to close this out but took note of @jhhr's suggestion and will get around to it in time.
