### ISSUE TITLE
excessive width when editing note types with many fields

### ISSUE THREAD

**Issue by Zaldroc8** [piazzatron/anki-smart-notes#4]
I have noticed that when editing a note type with many fields, the selection window expands excessively in width. This makes it difficult to navigate and you have to drag the window several times to reach the safe button.
Could the fields at the bottom be listed in a way that allows the window to be resized in width? This would greatly improve usability for more detailed note types.

**Comment by piazzatron** [comment]
This will be fixed in the next version! Thanks for the feedback :)

**Comment by piazzatron** [comment]
Fixed in 1.1.0. Can force an update via the Anki addon menu, or wait for it to roll out in auto-update (not sure how long Anki takes to pick up a new version).
