### ISSUE TITLE
Question: Does this still allow the use of a custom OpenAI API key?

### ISSUE THREAD

**Issue by l-qing** [piazzatron/anki-smart-notes#40]
I tried this plugin, and it's very good. 👍🏻

I saw in the previous issues https://github.com/piazzatron/anki-smart-notes/issues/16 that it was mentioned that a custom API key could be configured, but now it seems that there are no related configuration options in the advanced settings of the plugin.

![Shot 2024 10 24 at 00 38 36](https://github.com/user-attachments/assets/f00f3cf8-144e-48b7-8553-fa59f1941a29)

So I would like to inquire about this.

- Smart Notes V2.3.3
- MacOS

**Comment by piazzatron** [comment]
Hi @l-qing, glad you're finding smart notes useful!

I'm not currently supporting custom API keys for new users, unfortunately. This is something I am considering for the future, so your input is valuable here.
