### ISSUE TITLE
Issue with Addon: 403 Forbidden Error

### ISSUE THREAD

**Issue by hiratecs21** [piazzatron/anki-smart-notes#44]
Hey

The addon I purchased is not working and is showing this error:

403, message='Forbidden', url=URL('https://anki-smart-notes-server-production.up.railway.app/api/chat').

Could you please help me resolve this?

Thanks!

**Comment by piazzatron** [comment]
Hi, sorry about this! You should be fixed now. Closing this out, please re-open if you continue to hit issues. :)

(The anti-abuse system was triggered and was blocking your requests - this exists to prevent people from farming free trials).

**Comment by piazzatron** [comment]
Ah, just unblocked again + sent you an email to dan****@gmail.com
