### ISSUE TITLE
Smart Notes Error: Unknown error from OpenAI - 404

### ISSUE THREAD

**Issue by sethcoetzee** [piazzatron/anki-smart-notes#7]
**Description:**
I have recently installed the add-on, however haven't been able to get it to work despite using a paid chat-gpt API. It keeps giving me the following error message:

`Smart Notes Error: Unknown error from OpenAI - 404, message='Not Found', url=URL('https://api.openai.com/v1/chat/completions')`

Can anyone suggest what I may be doing wrong? I input the error message into ChatGPT itself, and it told me to adjust the URL path in one of the source files from `https://api.openai.com/v1/chat/completions` to `https://api.openai.com/v1/completions`, however doing so didn't fix the issue.

**Details:**
Anki Version ⁨24.06.2 (33a92379)⁩
Windows 10 Version 22H2

**Screenshot:**

![SmartNotes Error Message](https://github.com/piazzatron/anki-smart-notes/assets/76480967/3c8173c5-3865-418d-a375-a3d26b39caad)

**Comment by piazzatron** [comment]
Hi @sethcoetzee, sorry you're experiencing this. Can you confirm that you've paid for the OpenAI *API*, not just ChatGPT? It's unfortunately not enough to pay for ChatGPT premium, you also have to throw them $10 for a paid API key (nothing I can do about this limitation rn).

I'll add some improved error messaging around this case in the next version though

**Comment by piazzatron** [comment]
Going to close this one out, feel free to reopen @sethcoetzee if this didn't solve your issue

**Comment by sethcoetzee** [comment]
Thank you for the speedy response, I couldn't see where to get a paid API key at the time, but figured it out after your comment. All working now!
