### ISSUE TITLE
Please don't process promts with emty source fields. (anki-smart-notes)

### ISSUE THREAD

**Issue by hienstorfer** [piazzatron/anki-smart-notes#8]
I have defined several promts that should be processed with one note.
Now, source fields of a defined promt can be empty, then no processing sould occur. 
Currently, promts are send with emty fields with nonsense response.
can you please fix this?

**Comment by piazzatron** [comment]
Thanks for the flag @hienstorfer, will fix this in the next version

**Comment by piazzatron** [comment]
Fixed in v1.2.0

**Comment by hienstorfer** [comment]
Thank you! Its working now.
